print("Hello, world!")
print("Hee, hello there.")
print("Making quick progress.")
print("Funny")
print('Hey, does this still print?')
print("Ivo's computer does not work today.")
print('He said: "Hello."')
